import 'package:flutter/material.dart';
import '../../core/theme/app_theme.dart';
import '../../core/widgets/status_chip.dart';

class TripsPage extends StatelessWidget { const TripsPage({super.key}); @override Widget build(BuildContext context) => DefaultTabController(length: 4, child: Column(children: [
  Padding(padding: const EdgeInsets.fromLTRB(20,18,20,8), child: Row(children:[Expanded(child: Text('الرحلات',style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w900))),IconButton(onPressed:(){},icon:const Icon(Icons.search_rounded))])),
  const TabBar(isScrollable:true, tabs:[Tab(text:'متاحة'),Tab(text:'محجوزة'),Tab(text:'نشطة'),Tab(text:'مكتملة')]),
  const Expanded(child:TabBarView(children:[_TripList(status:'Available'),_TripList(status:'Booked'),_TripList(status:'Active'),_TripList(status:'Completed')]))
])); }
class _TripList extends StatelessWidget { const _TripList({required this.status}); final String status; @override Widget build(BuildContext context) { final rows=[('TRIP-2026-1042','جدة','الرياض','1,020 km','30,000 kg'),('TRIP-2026-1039','رابغ','الدمام','1,180 km','22,500 kg'),('TRIP-2026-1027','الدمام','جدة','1,250 km','18,000 kg')]; return ListView.separated(padding:const EdgeInsets.fromLTRB(20,16,20,24),itemCount:rows.length,separatorBuilder:(_,__)=>const SizedBox(height:10),itemBuilder:(_,i){final x=rows[i]; return InkWell(borderRadius:BorderRadius.circular(20),onTap:()=>_details(context,x),child:Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:AppColors.navy900,borderRadius:BorderRadius.circular(20),border:Border.all(color:AppColors.border)),child:Column(children:[Row(children:[Expanded(child:Text(x.$1,style:const TextStyle(fontWeight:FontWeight.w900))),StatusChip(label:status,tone:status=='Active'?StatusTone.success:status=='Completed'?StatusTone.neutral:StatusTone.accent)]),const SizedBox(height:14),Row(children:[_point(x.$2,'تحميل'),const Padding(padding:EdgeInsets.symmetric(horizontal:12),child:Icon(Icons.arrow_back_rounded,color:AppColors.orange)),_point(x.$3,'تسليم')]),const SizedBox(height:14),Row(children:[Text(x.$4,style:const TextStyle(color:AppColors.muted,fontSize:12)),const Spacer(),Text(x.$5,style:const TextStyle(color:AppColors.muted,fontSize:12)),const SizedBox(width:8),const Icon(Icons.chevron_left_rounded,color:AppColors.muted)]))])));}); }
Widget _point(String a,String b)=>Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:3),Text(b,style:const TextStyle(color:AppColors.muted,fontSize:11))]));
void _details(BuildContext context,(String,String,String,String,String) x){showModalBottomSheet(context:context,backgroundColor:AppColors.navy900,isScrollControlled:true,showDragHandle:true,builder:(_)=>Padding(padding:const EdgeInsets.fromLTRB(20,8,20,30),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[Text('تفاصيل الرحلة',style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w900)),const SizedBox(height:6),Text(x.$1,style:const TextStyle(color:AppColors.orange,fontWeight:FontWeight.w800)),const SizedBox(height:18),Text('${x.$2} → ${x.$3}'),const SizedBox(height:10),Text('الحمولة: ${x.$5}'),const SizedBox(height:10),Text('المسافة: ${x.$4}'),const SizedBox(height:22),SizedBox(width:double.infinity,height:50,child:FilledButton(onPressed:(){Navigator.pop(context);},child:Text(status=='Available'?'تأكيد الرحلة':'إغلاق')))])));}
}
